// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBz8oD12yBHDrO7g7xXxFxAeRRepVZWP1A',
    appId: '1:608843044150:web:259e7ac75fa4ce81764f97',
    messagingSenderId: '608843044150',
    projectId: 'msn-project-2e280',
    authDomain: 'msn-project-2e280.firebaseapp.com',
    storageBucket: 'msn-project-2e280.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQ5sWnj5iIdjkP1mh_DPUDY-tOQ-xL9Ds',
    appId: '1:608843044150:android:d6c9f4fa7cfe2ece764f97',
    messagingSenderId: '608843044150',
    projectId: 'msn-project-2e280',
    storageBucket: 'msn-project-2e280.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJmCcr-OwY6GjPxy2pou3fPWIh2SfgzJ4',
    appId: '1:608843044150:ios:5ad908df8516552f764f97',
    messagingSenderId: '608843044150',
    projectId: 'msn-project-2e280',
    storageBucket: 'msn-project-2e280.firebasestorage.app',
    iosBundleId: 'com.example.msnProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBJmCcr-OwY6GjPxy2pou3fPWIh2SfgzJ4',
    appId: '1:608843044150:ios:5ad908df8516552f764f97',
    messagingSenderId: '608843044150',
    projectId: 'msn-project-2e280',
    storageBucket: 'msn-project-2e280.firebasestorage.app',
    iosBundleId: 'com.example.msnProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBz8oD12yBHDrO7g7xXxFxAeRRepVZWP1A',
    appId: '1:608843044150:web:c8840814d55cff6d764f97',
    messagingSenderId: '608843044150',
    projectId: 'msn-project-2e280',
    authDomain: 'msn-project-2e280.firebaseapp.com',
    storageBucket: 'msn-project-2e280.firebasestorage.app',
  );
}
